# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlphaCalculator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlphaCalculator
   pod 'Anchors'
  pod 'SwiftOCR'
  pod 'TesseractOCRiOS'
  target 'AlphaCalculatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlphaCalculatorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
